config/routes.rb
Rails.application.routes.draw do

  root to: 'user/games#index'

  devise_for :users

  namespace :user do
    put 'preferences' => 'preferences#update'
    get 'preferences/edit' => 'preferences#edit'
    resources :televisions
    resources :channels, only: [:create]
    resources :games, only: [:index]
  end

  resources :leagues, only: [:index] do
    member do
      get 'competitors'
    end
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'users'

    resources :leagues, only: [:index] do
      member do
        get 'competitors'
      end
    end

    namespace :user do
      put 'preferences' => 'preferences#update'
      get 'preferences' => 'preferences#index'
      get 'preferences/:type' => 'preferences#index'
      resources :televisions, only: [:create, :index, :update, :destroy]
      resources :channels, only: [:create, :index, :destroy]
      resources :games, only: [:index]
    end

  end

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :competitors

  def as_json(options={})
    {
      id: id,
      name: name
    }
  end
end

app/controllers/api/leagues_controller.rb
class Api::LeaguesController < ApiController
  before_action :authenticate_user!

  def index
    render json: League.all
  end

  def competitors
    render json: League.find(params[:id]).competitors
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all.sort_by { |l| l.name }
  end

  def competitors
    @league = League.find(params[:id])
    @competitors = @league.competitors.sort_by { |c| c.name}
  end
end

app/views/leagues/competitors.html.erb
<div class="row">
  <div class="xs-col-12">
    <h2><%= "#{@league.name} Preferences" %></h2>
  </div>
</div>
<%= form_for :user, url: user_preferences_path, method: :put do |f| %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Competitor</th>
      </tr>
    </thead>
    <tbody>
      <% @competitors.each_with_index do |c, i| %>
        <tr>
          <% previous_preference = current_user.preferences.where(preference_type: "Competitor", preference_id: c.id) %>
          <% previous_rating = previous_preference.empty? ? 0 : previous_preference[0].amount %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][scale]", 2 %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][preference_type]", "Competitor" %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][preference_id]", c.id %>
          <td><%= check_box_tag "user[preferences_attributes][#{i}][amount]", 1, previous_rating == 1 %>  <%= c.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="form-group">
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/leagues/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2>League Preferences</h2>
  </div>
</div>
<% league_preferences = current_user.preferences.where(preference_type: "League") %>
<%= form_for :user, url: user_preferences_path, method: :put do |f| %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>League</th>
        <th>Personal Preference</th>
      </tr>
    </thead>
    <tbody>
      <% @leagues.each_with_index do |league, i| %>
        <tr>
          <% previous_preference = league_preferences.where(preference_id: league.id) %>
          <% previous_rating = previous_preference.empty? ? 0 : previous_preference[0].amount %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][scale]", 5 %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][preference_type]", "League" %>
          <%= hidden_field_tag "user[preferences_attributes][#{i}][preference_id]", league.id %>
          <td>
            <% if previous_preference.empty? %>
              <%= league.name %>
            <% else %>
              <%= link_to league.name, competitors_league_path(previous_preference[0].preference) %>
            <% end %>
          <td>
            <select name="user[preferences_attributes][<%=i%>][amount]">
              <option value="0" <%= "selected" if previous_rating == 0 %>>No Preference</option>
              <option value="1" <%= "selected" if previous_rating == 1 %>>1</option>
              <option value="2" <%= "selected" if previous_rating == 2 %>>2</option>
              <option value="3" <%= "selected" if previous_rating == 3 %>>3</option>
              <option value="4" <%= "selected" if previous_rating == 4 %>>4</option>
              <option value="5" <%= "selected" if previous_rating == 5 %>>5</option>
            </select>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="form-group">
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>