config/routes.rb
Rails.application.routes.draw do

  root to: 'user/games#index'

  devise_for :users

  namespace :user do
    put 'preferences' => 'preferences#update'
    get 'preferences/edit' => 'preferences#edit'
    resources :televisions
    resources :channels, only: [:create]
    resources :games, only: [:index]
  end

  resources :leagues, only: [:index] do
    member do
      get 'competitors'
    end
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'users'

    resources :leagues, only: [:index] do
      member do
        get 'competitors'
      end
    end

    namespace :user do
      put 'preferences' => 'preferences#update'
      get 'preferences' => 'preferences#index'
      get 'preferences/:type' => 'preferences#index'
      resources :televisions, only: [:create, :index, :update, :destroy]
      resources :channels, only: [:create, :index, :destroy]
      resources :games, only: [:index]
    end

  end

end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="logo" src="/assets/logo.png"/></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Televisions", user_televisions_path %></li>
        <li><%= link_to "Preferences", leagues_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div>
  </div>
</nav>